domain: zhuty18.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://zhuty18.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /zhuty18.github.io/      # place folder name if the site is served in a subfolder
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme